---
influxdb:
  host: 192.168.178.34
  port: 8086
  user: root
  password: root
  database: Water_Heater
  db_user: db_user
  db_password: db_password
  reconnect_interval: 10000
  write_interval: 10000
  voltage_measurement_name: voltage
  output_measurement_name: outputs
  state_measurement_name: state
  consumption_measurement_name: consumption
  mode_measurement_name: auto_mode
buffer:
  max_size: 1000
event_logger:
  publish: false
  print_level: DEBUG
gpio:
  regime_inputs:
    adsorb: 5
    float: 6
  relays_outputs:
    channels:
      - 26 # Output 1
      - 16 # Output 2
      - 13 # Output 3
      - 17 # Output 4
      - 23 # Output 5
      - 4 # Output 6
      - 20 # Output 7
      - 27 # Output 8
      - 12 # Output 9
      - 21 # Output 10
      - 05 # Output 11
      - 19 # Output 12
      - 25 # Output 13
  voltage_sensor:
    address: 0x48
    channel: 0
    scale_min: 50
    scale_max: 60
controller:
  control_interval: 2
  loads:
    - 0.33
    - 0.4
    - 0.444
    - 0.5
    - 0.667
    - 0.723
    - 0.75
    - 0.8
    - 0.833
    - 0.907
    - 1
    - 1.111
    - 1.2
    - 1.333
    - 1.5
    - 1.667
    - 1.75
    - 2.0
    - 2.5
    - 2.667
    - 3.0
    - 3.667
    - 4.0
  voltage_critical_level: 47
  voltage_absorb_limit_min: 56
  voltage_absorb_limit_max: 57
  voltage_float_limit_min: 54
  voltage_float_limit_max: 55
simulation:
  active: False