---
influxdb:
  host: 192.168.178.34
  port: 8086
  user: root
  password: root
  database: Water_Heater
  db_user: db_user
  db_password: db_password
  reconnect_interval: 10000
  write_interval: 10000
  voltage_measurement_name: voltage
  output_measurement_name: outputs
  state_measurement_name: state
  consumption_measurement_name: consumption
  mode_measurement_name: auto_mode
buffer:
  max_size: 100
event_logger:
  publish: false
  print_level: DEBUG
gpio:
  regime_inputs:
    adsorb: 5
    float: 6
  relays_outputs:
    address: 0x27
    channels:
      - 1 # Output 1
      - 2 # Output 2
      - 3 # Output 3
      - 4 # Output 4
      - 5 # Output 5
      - 6 # Output 6
      - 7 # Output 7
      - 8 # Output 8
  voltage_sensor:
    address: 0x10
    channel: 0
    scale_min: 50
    scale_max: 60
controller:
  control_interval: 3
  loads:
    - 0
    - 0.33
    - 0.5
    - 0.67
    - 1
    - 1.5
    - 2
    - 3
  voltage_critical_level: 47
  voltage_absorb_limit_min: 56
  voltage_absorb_limit_max: 57
  voltage_float_limit_min: 54
  voltage_float_limit_max: 55
simulation:
  active: True
  profile: constant