---
influxdb:
  host: 192.168.178.34
  port: 8086
  user: root
  password: root
  database: Water_Heater
  db_user: db_user
  db_password: db_password
  reconnect_interval: 10000
  write_interval: 10000
  voltage_measurement_name: voltage
  output_measurement_name: outputs
  state_measurement_name: state
  consumption_measurement_name: consumption
  mode_measurement_name: auto_mode
buffer:
  max_size: 100
event_logger:
  publish: false
  print_level: DEBUG
controller:
  control_interval: 5
  voltage_sensor_channel: 0
  voltage_scale_min: 50
  voltage_scale_max: 60
  output_channels:
    - 5 # Output 1
    - 6 # Output 2
    - 12 # Output 3
    - 13 # Output 4
    - 16 # Output 5
  loads:
    - 0
    - 0.33
    - 0.5
    - 0.67
    - 1
    - 1.5
    - 2
    - 3
  voltage_threshold: 0.1
  voltage_critical_level: 47
  voltage_limit_min: 57
  voltage_limit_max: 58
  input_simulation: False
  simulation_profile: sine